### ISSUE TITLE
Error serving metrics due to possible duplicate values

### ISSUE THREAD

**Issue by Neal** [redpanda-data/kminion#133]
I am getting this error from the metrics endpoint which I believe may be thrown from the prometheus collector:

```
$ curl http://localhost:8080/metrics -v
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Mon, 27 Dec 2021 13:22:08 GMT
< Transfer-Encoding: chunked
<
An error has occurred while serving metrics:

10 error(s) occurred:
* collected metric "kminion_kafka_consumer_group_info" { label:<name:"coordinator_id" value:"1" > label:<name:"group_id" value:"walreader" > label:<name:"protocol" value:"cooperative-sticky" > label:<name:"protocol_type" value:"consumer" > label:<name:"state" value:"Stable" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_members" { label:<name:"group_id" value:"walreader" > gauge:<value:6 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_members" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"oms-v2-live.wal.v1" > gauge:<value:2 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_members" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"sandbox.oms-v2-paper.wal.v1" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_members" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"oms-v2-paper.wal.v1" > gauge:<value:2 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_members" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"sandbox.oms-v2-live.wal.v1" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_assigned_partitions" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"oms-v2-live.wal.v1" > gauge:<value:128 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_assigned_partitions" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"sandbox.oms-v2-paper.wal.v1" > gauge:<value:32 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_assigned_partitions" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"oms-v2-paper.wal.v1" > gauge:<value:128 > } was collected before with the same name and label values
* collected metric "kminion_kafka_consumer_group_topic_assigned_partitions" { label:<name:"group_id" value:"walreader" > label:<name:"topic_name" value:"sandbox.oms-v2-live.wal.v1" > gauge:<value:64 > } was collected before with the same name and label values
* Connection #0 to host localhost left intact
```

I am not sure if I have it set up incorrectly or why there is a collision. I have a consumer group with the same name for multiple topics -- could that cause any issues?

**Comment by weeco** [comment]
Hey @Neal ,
this metric is supposed to report the number of assigned partitions per topic. Accordingly there should only be one unique metric series per <consumergroup, topic> tuple. 

I'll have a look at the code why this may be happening. Could you please add what kminion version you are using? If you are not already using the latest version please give it a shot. This version has been tested in clusters with many consumer groups, so I'm kind of surprised this is happening if you are using a recent version.

**Comment by Neal** [comment]
I am using the latest (v2.2.0) version already. Let me know what you find or if you need anything else from me. Thanks!

**Comment by weeco** [comment]
Hey @Neal ,
I just double checked how it would be possible that `kminion_kafka_consumer_group_info` for the same label keypairs would be reported multiple times. I looked at that specific metric because it's the most straightforward one in the code. 

Anyways, I didn't find an issue with the code and since I have tested this successfully against tens of Kafka clusters with hundreds of consumer groups I would expect that this must be some specific scenario. Hence a few follow up questions:

1) Do you always get that response or was that just a single occurence? (Wondering whether this only happens when the group coordinator changes or so)
2) Do you happen to know how to reproduce this?
3) What config do you use for `minion.consumerGroups.scrapeMode`. Can either be `adminApi` or `offsetsTopics`. By default it is `adminApi`
4) Do you run Kowl (or another tool) which describes consumer groups so that we can see what the Kafka API reports when describing consumer groups? I'm wondering whether we would see the same group in the response twice as well (shouldn't cause an error there, because we are not looking for duplicate ids there).
5) What Kafka version do you use?

**Comment by Neal** [comment]
> 1. Do you always get that response or was that just a single occurence? (Wondering whether this only happens when the group coordinator changes or so)

Always getting it on our prod env. We have a staging env with similar set up where it works fine with the same kminion config.

> 2. Do you happen to know how to reproduce this?

Sorry but not exactly. I just deployed it the same way to our prod env as I did earlier to our staging but I keep getting this error on prod.

> 3. What config do you use for `minion.consumerGroups.scrapeMode`. Can either be `adminApi` or `offsetsTopics`. By default it is `adminApi`

It is `adminApi`.

> 4. Do you run Kowl (or another tool) which describes consumer groups so that we can see what the Kafka API reports when describing consumer groups? I'm wondering whether we would see the same group in the response twice as well (shouldn't cause an error there, because we are not looking for duplicate ids there).

We do not.

> 5. What Kafka version do you use?

We actually use Redpanda so not completely sure but will try to find out.

Let me know if you need anything else and I will also try a few things to possibly narrow down. Thanks!

**Comment by weeco** [comment]
> Always getting it on our prod env. We have a staging env with similar set up where it works fine with the same kminion config.

Ok that's good, this way we can figure out what's going wrong at least. Currently I think the only way that this issue can happen is that we receive the same consumer group at least twice in the `DescribeConsumerGroups` Kafka API response.

Ideally you could run another tool like Kowl (https://github.com/cloudhut/kowl) to list your consumer groups and then we can see what is returned by the API. But there are also other CLI tools. Maybe that clarifies a few things. Without that information I'm currently a bit clueless and I would need to have another look to see how this could happen.

**Comment by Neal** [comment]
I installed kowl and it reports only one consumer group. I will try to find out how to see raw API response. If it's easier, I believe you are on the Redpanda slack (it's where I found out about kminion) so happy to discuss there further.

**Comment by srvmsr** [comment]
Hi @Neal  di you found any solution to this issue , I am also seeing same error , had to disable consumergroups scraping to run kminion for redpanda

**Comment by Neal** [comment]
@srvmsr yes, I was running an older Redpanda and the issue was solved after upgrading to a newer version.
