### ISSUE TITLE
Failed to decode consumer group member assignment when consumer group is rebalancing

### ISSUE THREAD

**Issue by Sh1ftry** [redpanda-data/kminion#141]
My kminion deployment is logging below error message from time to time.
```json
{
  "level": "error",
  "ts": "2022-04-04T08:04:39.946Z",
  "logger": "main.prometheus",
  "msg": "failed to decode consumer group member assignment, internal kafka error",
  "group_id": "amazon.msk.canary.group.broker-1",
  "assignment_decode_failures": 1
}
```
After some digging I found out that it happens when consumer group is in `PreparingRebalance` state and its members have not yet been assigned any partitions. I think [`membersWithEmptyAssignment`](https://github.com/redpanda-data/kminion/blob/2a62a9d24ca6579cc5dcf30c4f56215430162fd4/prometheus/collect_consumer_groups.go#L68) should be increased when `member.MemberAssignment` is empty instead of failing to read it in [`decodeMemberAssignments`](https://github.com/redpanda-data/kminion/blob/2a62a9d24ca6579cc5dcf30c4f56215430162fd4/prometheus/collect_consumer_groups.go#L143).

**Comment by doryer** [comment]
Same issue here
