### ISSUE TITLE
How calculate partition lag and partition offset in kafka minion v2.2.0

### ISSUE THREAD

**Issue by osipovdaniil** [redpanda-data/kminion#152]
Hi there! Please help me
1. In kafka minion v1.0.0 we have metrics `kafka_minion_group_topic_partition_lag` But in version 2.2.0 doesn't have this metric. How can i get partition lag?
2. How can i calculate `kafka_minion_group_topic_partition_offset` in kafka minion v2.2.0?

**Comment by osipovdaniil** [comment]
1. I see metrics `kminion_kafka_consumer_group_topic_partition_lag` its resolve
2. Metrics `kafka_minion_group_topic_partition_offset` likewise `kminion_kafka_topic_partition_high_water_mark`

**Comment by weeco** [comment]
Hey @osipovdaniil ,
yes both of your answers/assumptions are correct.
