### ISSUE TITLE
I need a proper Helm chart how to edit the Kafka cluster Endpoint in that

### ISSUE THREAD

**Issue by keyansaravanan** [redpanda-data/kminion#156]
Needed in a three to four commands

**Comment by weeco** [comment]
It is already possible to configure the bootstrap brokers with the existing Helm chart, see here: https://github.com/redpanda-data/kminion/blob/5425c6203c957ad1688bb60d5e8eb9bb2bdaaa63/charts/kminion/values.yaml#L144
