### ISSUE TITLE
Monitoring mulitple cluster

### ISSUE THREAD

**Issue by ut0mt8** [redpanda-data/kminion#162]
Hello folks and thanks for this piece of software. I'm happy to see that kafka-minion had greatly evolved since the last time I use it.

I got a question tough: I have multiple kafka-cluster to monitor with kminion. I suppose I need  multiple instance of kminion running, each for one of them. But how I can distinguish metrics? I saw a "namespace" config stanza. Great but it change the names of the metrics and so I ll need to adapt every dashboard, and make multiple dashboard..

Is there another label I can use to select the cluster?

**Comment by s2504s** [comment]
Hi @ut0mt8 
Life is pain :) 
You have the two chairs:
* Setup additional kminion-exporter, Prometheus and Grafana
* Add an additional label and modify your dashboards

We took chair number two:
Using dedicated kminion-eporter for each Kafka cluster but just one Prometheus and one Grafana
Also we added the additional label for each cluster to ServiceMonitor - `cluster: my-X-cluster` and yes - dashboards have been modified too
