### ISSUE TITLE
Documentation: Wrong type of the metric `kminion_kafka_consumer_group_topic_offset_sum`

### ISSUE THREAD

**Issue by s2504s** [redpanda-data/kminion#165]
Hi, there!
It looks like is a mistake in the metric description:
```
# TYPE kminion_kafka_consumer_group_topic_offset_sum gauge
```
But it seems to me this is a counter

![image](https://user-images.githubusercontent.com/1134449/186439853-f4db20c5-0f32-4b71-b872-720c4e27e8f0.png)

https://github.com/redpanda-data/kminion/blob/master/docs/metrics.md

**Comment by weeco** [comment]
This is a gauge but the monotonic increase is expected as Kafka offsets are append only. The offset sum / high water marks can not suddenly drop, unless we remove partitions or similar.
