### ISSUE TITLE
The latest helm chart version 0.11.1 refers to image v2.2.3, that does not exist in the repository. 

### ISSUE THREAD

**Issue by KuznetsovDenis** [redpanda-data/kminion#200]
After installing helm chart, the pod is in invalid state. The reason: Image 'quay.io/cloudhut/kminion:v2.2.3' not found in repository.  
The latest available image version is v2.2.0.

**Comment by weeco** [comment]
Thanks @KuznetsovDenis - the docker repository hasn't been updated. I filed a PR to address this
