### ISSUE TITLE
Add support for SASL/OAUTHBEARER

### ISSUE THREAD

**Issue by bachmanity1** [redpanda-data/kminion#223]
https://github.com/redpanda-data/kminion/blob/2f841e31aff86138def1b1e3716324ade8efe56c/kafka/config_sasl.go#L40-L41

We've been using kminion to monitor consumer group lags and so far our experience has been great, but soon we are planning to make all our Kafka clusters use `SASL/OAUTHBEARER` and it looks like we won't be able to use kminion anymore. 

Can you please add support for `SASL/OAUTHBEARER`? Thanks!

**Comment by weeco** [comment]
@bachmanity1 Please go ahead. You can have a look at the Console repository where OAuthBearer is already supported.

**Comment by bachmanity1** [comment]
@weeco I've opened PR https://github.com/redpanda-data/kminion/pull/230

**Comment by bachmanity1** [comment]
resolved by #230.
