### ISSUE TITLE
Expose Kafka retention.bytes and partitions Over Time in a new metric

### ISSUE THREAD

**Issue by selsabil94** [redpanda-data/kminion#234]
Currently, the kminion_kafka_topic_info metric provides valuable insights into Kafka topic information, but lacks a dedicated metric for tracking retention.bytes and number of partitions over time. This enhancement aims to expose the retention.bytes and partitions information as a standalone metric, providing a clear and detailed view of data retention bytes and partitions information.
This additional metric will enhance monitoring capabilities and allow users to track the growth and patterns of retention bytes/partitions, facilitating better capacity planning and resource management

**Comment by weeco** [comment]
Closing this for now, see ref: https://github.com/redpanda-data/kminion/pull/235#issuecomment-1937059102

With a different design we may consider it, exposing topic configurations via prometheus metric is not an ideal usecase though. Would be interesting to learn why one wants to track the topic configuration values historically via Prometheus
